### ISSUE TITLE
Clean up of code

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/go-alpm#24]
All over the code base there are some functions that take a `Handle` and others that take a `*Handle`. This should probably be changed to one of the other, I'm not sure which though. With a pointer you can check for null. But as this struct basically just wraps a c pointer we could just add a .IsNil() method to check the inner pointer.

Also there are a couple of places where `...type` is used. `[]type` should probably be used instead.

**Comment by Jguer** [comment]
I would settle on `*Handle` just for C nostalgia

But yes, this code is in heavy need of clean up and documentation

**Comment by Morganamilo** [comment]
Also similar to https://github.com/Jguer/yay/issues/759, the code could be split into distinct modules (db, package, ect) What do you think about that?

**Comment by Morganamilo** [comment]
I'm getting to this now and Handle is used more than *Handle. As well as that the Db, Package and similar structs all take a Handle and not a *Handle so I believe it's probably better to do it the other way.

**Comment by Morganamilo** [comment]
But looking at it further, Because Db holds a Handle. If there's an error getting a db then we can't return return nil, we have to return Db{Handle{}, nil}.

So I guess pointers it is after all maybe?

**Comment by Jguer** [comment]
I would say pointers after all, just seems more intuitive
