### ISSUE TITLE
example codes are not working as expected.

### ISSUE THREAD

**Issue by shyaminayesh** [Jguer/go-alpm#39]
seems like examples are not working as expected.

**Comment by Jguer** [comment]
You're right, I'll update them tonight.

Don't forget you must `go get github.com/jguer/go-alpm` if you're just using them separately if you want to avoid

```
installed.go:13:2: cannot find package "github.com/jguer/go-alpm" in any of:
```

**Comment by shyaminayesh** [comment]
@Jguer thank you very much. looking forward to see the new examples. 

Do I need to run the go executable as root to query the packages ?

**Comment by Jguer** [comment]
You should not need root to query the packages

```shell
$ go get github.com/Jguer/go-alpm
$ git clone https://github.com/Jguer/go-alpm.git
$ cd go-alpm
$ go run examples/installed.go
```
Should be all you need to run the example of installed packages

**Comment by shyaminayesh** [comment]
> You should not need root to query the packages
> 
> ```shell
> $ go get github.com/Jguer/go-alpm
> $ git clone https://github.com/Jguer/go-alpm.git
> $ cd go-alpm
> $ go run examples/installed.go
> ```
> 
> Should be all you need to run the example of installed packages

I tried to clone the repo and run the examples and the ```installed.go``` successfully returns packages that installed in my ArchLinux system, but when I run ```updates.go``` it always return **Total Download Size: 0.0 B**

If I understand correctly this ```updates.go``` script need to pull the packages that have updates available ?

**Comment by shyaminayesh** [comment]
@Jguer any idea why is that happening ?
