### ISSUE TITLE
examples/updates.go not working as expected.

### ISSUE THREAD

**Issue by shyaminayesh** [Jguer/go-alpm#40]
This is related to the #39 and after @Jguer push new examples I tried to clone the repo and run the examples and the ```installed.go``` successfully returns packages that installed in my ArchLinux system, but when I run ```updates.go``` it always return **Total Download Size: 0.0 B**

If I understand correctly this updates.go script need to pull the packages that have ending updates available ? ( I have packages with pending updates in my system )

**Comment by shyaminayesh** [comment]
@Jguer can you please confirm this behaviour or kindly take a look into it ?

**Comment by Jguer** [comment]
https://github.com/Jguer/yay/blob/next/config.go#L374

I confirm, there's no configuration of the alpm handle so you need to take a page of yay and configure the alpm handle, the examples need to be updated for this

**Comment by shyaminayesh** [comment]
@Jguer got it sorted out, I'll make a PR to updates example in the evening. Thank you very much for the info.
