### ISSUE TITLE
Currently fails to build with Pacman 6

### ISSUE THREAD

**Issue by mpldr** [Jguer/go-alpm#43]
When building with the latest pacman-git build (`6.0.0alpha1.r99.g558d08d8-1`), it fails:
```
# github.com/Jguer/go-alpm/v2
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.0.2/handle.go:430:10: could not determine kind of name for C.alpm_option_get_arch
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.0.2/handle.go:436:10: could not determine kind of name for C.alpm_option_set_arch
```

This may be due to a change in Pacman 6 or just a Pacman Bug, however, I doubt that they accidentally removed two related functions, so probably the former.

**Comment by x1b6e6** [comment]
PR at #42

**Comment by poldi1405** [comment]
Is the dropped support for PM Alphas official now @Jguer?

**Comment by Morganamilo** [comment]
Yep, use pacman-git if you want the new stuff.

**Comment by poldi1405** [comment]
I am, would be great to use yay alongside.

**Comment by Morganamilo** [comment]
#45 is the only other api change I believe

**Comment by Jguer** [comment]
`pacman-git` is supported and `yay-git` should now support it @poldi1405 

The fixed version pacman-alpha (aka 6.0.0alpha1.r0...) is not supported

**Comment by Morganamilo** [comment]
#45 needs to be implemented too to support it.

**Comment by Jguer** [comment]
> #45 needs to be implemented too to support it.

:+1: @Morganamilo , I see you've already passed a review on it, feel free to merge it when you think it's ready

**Comment by Morganamilo** [comment]
I know alpm very well but not golang anymore. My review is more on the implementation. You can review the actual code :P

**Comment by camdenorrb** [comment]
Welp, Yay doesn't work on the new Pacman 6 which is in the core now

**Comment by Fooftilly** [comment]
> Welp, Yay doesn't work on the new Pacman 6 which is in the core now
> 
> Related issue: [Jguer/yay#1518](https://github.com/Jguer/yay/issues/1518)

Same with me, it gives out an error: yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory

**Comment by pineman** [comment]
@camdenorrb yes it does - its just that a rebuild is required. I did not experience the issue you linked, and can't reproduce it on a clean install (e.g. on docker)

**Comment by Jguer** [comment]
Closed already with https://github.com/Jguer/go-alpm/pull/42
